README.md

Added a hero image to the README. (We may want to add the image itself to the repo, instead of reference it out on the web.)

docs: add hero to README

---

cli.js
package.json

This PR adds a cli to the package so a user can run:
```bash
mercury-parser [url-to-parse]
```
And get a JSON response for the url passed.

feat: add mercury-parser cli

---

package.json
yarn.lock

This PR removes the `all-contributors-cli` package from `devDependencies` and the scripts. Since mercury-parser is no longer using them it is better to remove these.

chore: remove all-contributors-cli deps and script since no longer used

---

CHANGELOG.md
package.json

release: 1.1.1

---

src/resource/index.js

For now just reverting to original for browser.

fix: jquery doesn't like the case insensitive meta content selector

---

fixtures/nock/mercury-test.js
src/mercury.js
src/mercury.test.js

The check for errors on an HTTP request was happening after calling `getExtractor`. This caused problems because `getExtractor` isn't meant to receive an error object. Returning before `getExtractor` fixes this.

Handle HTTP errors.

---

src/extractors/custom/deadspin.com/index.js

Use the same parser for all websites listed at Kinja.com since they are all published on the same platform and share the same structure.
Addresses #219

feat: Use Deadspin parser for all Kinja websites

---

package.json
yarn.lock

Updates `watchify` to 3.11.1, which removes the transitive dependency on `hoek`, which has a vulnerability.

feat: upgrade watchify to remove vulnerable hoek dep

---

package.json
src/resource/utils/fetch-resource.js
yarn.lock

The forked `request` we're using now has some old dependencies that have
CVEs.
`postman-request` is a drop-in replacement for `request` that includes some
fixes that aren't in upstream `request` yet, and is recommended by
@czardoz:
https://github.com/czardoz/request/commit/7cdd4d4efc3984278236eb3f2f0e1f3889b43b90#commitcomment-27440593

feat: switch from forked request to postman-request

---

src/utils/text/fixtures/html.js
src/utils/text/normalize-spaces.js
src/utils/text/normalize-spaces.test.js

Addresses #310 
Preserve whitespace in the the following HTML elements:
- `<code>`
- `<pre>`
- `<textarea>`

fix: Preserve whitespace in certain HTML elements

---

README.md
cli.js
dist/mercury.js
src/extractors/custom/README.md
src/extractors/root-extractor.js
src/extractors/root-extractor.test.js
src/mercury.js
src/mercury.test.js
src/utils/dom/make-links-absolute.js

Adds an `extend` option that lets you add custom types to be extracted
and returned alongside the defaults, either in a call to `parse()` or in
a custom extractor.
```
Mercury.parse(
url,
{
extend: {
last_edited: { selectors: ['#last-edited'] }
}
}
)
```
or on the command line:
```
mercury-parser https://www.nytimes.com/interactive/2019/03/11/magazine/regina-hall-movies-black-audience.html \
--extend kicker=.kicker \
--extend credits=.rad-article-credits \
--extend-list captions=.rad-caption-text
```

feat: extract custom types with extend option

---

src/mercury.test.js
src/resource/index.test.js
src/resource/utils/fetch-resource.js
src/resource/utils/fetch-resource.test.js

Indicate that non-200 status codes are rejected, as opposed to "non-2xx".
In terms of HTTP GET requests for content on the web, the status code that makes most sense as a response containing content that would eventually be parseable by Mercury is 200, the other 2xx level status codes are more suited for API requests, and typically contain different kinds of content in the responses, e.g. 204 indicates "No Content", 206 indicates "Partial Content", etc...
The 202 status code, while in fact used to indicate that the request has been "Accepted", is used to indicate that the processing for the request has not been completed, and is expected to contain:
>the request's current status and point to (or embed) a status monitor that can provide the user with an estimate of when the request will be …

fix: Explicity reject non-200 status codes

---

src/resource/index.js
src/resource/index.test.js

(This is a re-creation of #179; I did something weird with my fork 🍴)
This may be exceedingly rare, but if the response does not include a
Content-Type header, the parser will raise an exception. This fix ensures that
even if the header is not present, the value we check is still a string.
I discovered this issue while trying to parse my own site, and while I've fixed
the headers there, I left one bad URL for verification:
https://johnholdun.com/404

fix: Initialize Content-Type as empty string if not present

---

src/utils/dom/make-links-absolute.js

Don't attempt to transform empty `href` and `src` attributes into absolute URLs.
This was breaking the web build tests since both CNN URLs used for the tests (http://www.cnn.com/2016/11/05/middleeast/iraq-mosul-isis-offensive/ and https://www.cnn.com/2019/01/30/politics/trump-intel-chiefs-foreign-policy-iran-isis-north-korea/index.html) contain the following tag in the document `head`
```html
<link rel="dns-prefetch" href="" />
```

fix: skip absolutizing empty hrefs

---

src/utils/dom/make-links-absolute.js
src/utils/dom/make-links-absolute.test.js

Skip attempting to absolutize empty or invalid `srcset` attributes..
Addresses #385

fix: skip absolutizing invalid srcsets

---

fixtures/deadline.com/1555363730240.html
fixtures/deadline.com/1556104756617.html
src/extractors/custom/deadline.com/index.js
src/extractors/custom/deadline.com/index.test.js
src/extractors/custom/index.js

add deadline.com custom parser

feat: add deadline.com custom parser

---

.circleci/config.yml
package.json

This PR: 
- updates the minimum required node version from 8 to 10
- updates CircleCI's node image

chore: update node version

---

package.json

Greenkeeper stopped their services in June and migrated to [synk](https://snyk.io/)
This PR clears any configs related to greenkeeper and we can continue using depandabot.

chore: remove greenkeeper configs

---

src/extractors/custom/ici.radio-canada.ca/index.js
src/extractors/custom/www.dmagazine.com/index.js

These extractors were variously failing tests as I tried updating dependencies. It seems like some of the format detection logic has changed, and making these date detectors more explicit fixes them.
As long as the tests for these extractors continue to pass, we should be good to merge this commit. Then #656 should turn green as well.

feat: Add date formats to two extractors

---

src/resource/index.js
src/resource/index.test.js

Fixes #490 (I think!) and adds a test case for the bug that fails on `master`.
https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding#solution says "In general, keep in mind that all javascript strings are already decoded and should not be decoded again."
Per that note, I think the charset-detection logic in `encodeDoc` should be skipped entirely when using a `preparedResponse`, to prevent double-decoding the html string.  Instead we should assume that the caller has already decoded the content when a `preparedResponse` has been provided.

fix: don't try to re-decode prepared response

---

package.json
rollup.config.esm.js

Today, if you want to user mercury in the browser, you can pull it in via a `<script>` tag from [a CDN like unpkg](https://unpkg.com/browse/@postlight/mercury-parser@2.2.0/dist/) as an iife.
```html
<script src="https://unpkg.com/@postlight/mercury-parser@2.2.0/dist/mercury.web.js"></script>
```
Would be nice if there was an ES modules build, so then you could import it directly:
```js
import Mercury from "https://unpkg.com/@postlight/mercury-parser@2.3.0/dist/mercury.esm.js"
```
It seems like this would be pretty straightforward. I'm not entirely sure how the build is set up, but mimicking what I saw with the `build:web` scripts, I added one for ES Modules. Tested locally and it produced a build file (`dist/mercury.esm.js`) which I could import myself in a local project.
Note: I had to …

Feature Request: Support an ES Modules Dist Build

---

scripts/check-build.test.js

Modifies `scripts/check-build.test.js` to differentiate between browser environments and non-browser environments title string.

chore: modifies check build test to differentiate between test environments

---

src/utils/dom/convert-to-paragraphs.js

Based on this comment: https://github.com/postlight/mercury-parser/issues/530#issuecomment-580105171

feat: Add figcaption to list of non-convertible span parents

---

src/extractors/collect-all-pages.js
src/extractors/custom/medium.com/index.js
src/extractors/custom/techlog.iij.ad.jp/index.test.js
src/extractors/generic/word-count/extractor.js
src/extractors/root-extractor.js
src/mercury.test.js
src/resource/utils/dom/convert-lazy-loaded-images.js

This PR includes fixes a number of issues related to the core functionality of @postlight/parser.
Change Log:
- fixes issue where parser would return incorrect `word_count` if not contained within a root div element. ([#617](https://github.com/postlight/parser/issues/617))
- replaces `pages_rendered` key with `rendered_pages` for consistency amongst single & multi-page parse results. ([#558](https://github.com/postlight/parser/issues/558))
- fixes issue where no lead_image_url would be found if multiple `og:image` meta tags are present ([#592](https://github.com/postlight/parser/issues/592))
- fixes issue with lazy loaded images returning a JSON object as the image src. ([#589](https://github.com/postlight/parser/issues/589))
- fixes issue with initial drop cap character being filtered by …

maintenance update - october 2022

---

src/extractors/custom/postlight.com/index.js

This PR addresses [this issue](https://github.com/postlight/parser/issues/706) by adjusting the selectors in Postlight.com's custom selector. I had to expand the main content's selector and then exclude a few elements from within it. That way the hero image gets pulled in as part of the content and can be displayed by the Reader.
Note that the Parser does successfully select the hero image and emit it to the Reader as the `lead_image_url`, but that the Reader does not make use of that field for anything. So there might be a bigger design/product question to explore there. This is a reasonable fix in the meantime.

adjust postlight insights custom selectors

---

src/extractors/root-extractor.js

This PR solves the above issue by selecting extended types before nodes get removed/cleaned during content selection. 
**Before:**
- Adding extended types via the command line was functional, but adding via the API with `addExtractor` was producing null extended values when custom extractors lacked a `content` key. This is because `root-extractor.js` was executing `selectExtendedTypes` after content extraction, which involves the removal of various nodes in the DOM tree. Consequently, some extended types failed to appear.
**After:**
- After this PR, `selectExtendedTypes` executes before content fetching in order to traverse the DOM before cleaning.

fix: 721 | custom extractor extend bug
