README.md
=> docs: add npm install instructions

.circleci/config.yml
CI config needs filters on all jobs referenced from other jobs with filters.
=> fix: ci config

cli.js
Adds basic error handling/messaging to the cli.
Closes #248.
=> feat: handle cli errors/timeout

README.md
=> docs: add instructions for cli to README

cli.js
=> fix: parse signature in cli

README.md
Extra semicolon that I noticed didn't need to be here.
=> Chore: delete extra semicolon

dist/generate-custom-parser.js, dist/mercury.js, scripts/rollup.config.js
- swap fs import
- fix rollup config
=> fix: custom parser generator

.circleci/config.yml
=> fix: ci artifact paths

src/mercury.js, src/mercury.test.js, src/resource/index.test.js, src/resource/utils/fetch-resource.js, src/utils/errors.js, src/utils/index.js
Addresses #279 , to help users identify the exact reason/error for failed parse attempts
=> feat: Return specific errors on failed parse attempts

README.md
Add documentation for parsing custom/pre-fetched HTML, in reference to #324
=> docs: Add parsing custom HTML to README.md

scripts/comment-for-pr.js
Simply removes an import of a file that no longer exists.
=> chore: remove unneeded import

CODE_OF_CONDUCT.md
Just fixes a tiny typo in the CoC. Line 12 is the only one I actually edited, but it looks like some markdown linting happened or something?
=> chore: small CoC typofix

fixtures/otrs.com/1553117632270.html, src/extractors/custom/index.js, src/extractors/custom/otrs.com/index.js, src/extractors/custom/otrs.com/index.test.js
=> feat: add otrs.com custom parser

fixtures/phpspot.org/1554622277068.html, src/extractors/custom/index.js, src/extractors/custom/phpspot.org/index.js, src/extractors/custom/phpspot.org/index.test.js
=> feat: add phpspot.org custom parser

fixtures/www.infoq.com/1554555811551.html, src/extractors/custom/index.js, src/extractors/custom/www.infoq.com/index.js, src/extractors/custom/www.infoq.com/index.test.js
=> feat: add www.infoq.com custom parser

fixtures/www.moongift.jp/1554559177617.html, src/extractors/custom/index.js, src/extractors/custom/www.moongift.jp/index.js, src/extractors/custom/www.moongift.jp/index.test.js
=> feat: add www.moongift.jp custom parser

fixtures/www.itmedia.co.jp/1550977733079.html, src/extractors/custom/index.js, src/extractors/custom/www.itmedia.co.jp/index.js, src/extractors/custom/www.itmedia.co.jp/index.test.js
www.itmedia.co.jp custom parser
=> feat: add www.itmedia.co.jp custom parser

fixtures/www.publickey1.jp/1554481347071.html, src/extractors/custom/index.js, src/extractors/custom/www.publickey1.jp/index.js, src/extractors/custom/www.publickey1.jp/index.test.js
www.publickey1.jp custom parser
=> feat: add www.publickey1.jp custom parser

fixtures/bookwalker.jp/1554821842273.html, src/extractors/custom/bookwalker.jp/index.js, src/extractors/custom/bookwalker.jp/index.test.js, src/extractors/custom/index.js
=> feat: add bookwalker.jp custom parser

src/extractors/custom/jvndb.jvn.jp/index.js, src/extractors/custom/jvndb.jvn.jp/index.test.js
fix: add date_published selector
=> fix: add date_published selector

fixtures/www.yomiuri.co.jp/1554993242061.html, src/extractors/custom/index.js, src/extractors/custom/www.yomiuri.co.jp/index.js, src/extractors/custom/www.yomiuri.co.jp/index.test.js
add www.yomiuri.co.jp custom parser
=> feat: add www.yomiuri.co.jp custom parser

fixtures/japan.cnet.com/1555118717655.html, src/extractors/custom/index.js, src/extractors/custom/japan.cnet.com/index.js, src/extractors/custom/japan.cnet.com/index.test.js
add japan.cnet.com custom parser
=> feat: add japan.cnet.com custom parser

fixtures/weekly.ascii.jp/1555849300154.html, src/extractors/custom/index.js, src/extractors/custom/weekly.ascii.jp/index.js, src/extractors/custom/weekly.ascii.jp/index.test.js
=> feat: add weekly.ascii.jp custom parser

fixtures/techlog.iij.ad.jp/1556573200354.html, src/extractors/custom/index.js, src/extractors/custom/techlog.iij.ad.jp/index.js, src/extractors/custom/techlog.iij.ad.jp/index.test.js
techlog.iij.ad.jp custom parser
=> feat: add techlog.iij.ad.jp custom parser

fixtures/wired.jp/1556585529692.html, src/extractors/custom/index.js, src/extractors/custom/wired.jp/index.js, src/extractors/custom/wired.jp/index.test.js
=> feat: add wired.jp custom parser

fixtures/japan.zdnet.com/1556591023244.html, src/extractors/custom/index.js, src/extractors/custom/japan.zdnet.com/index.js, src/extractors/custom/japan.zdnet.com/index.test.js
=> feat: add japan.zdnet.com custom parser

fixtures/www.rbbtoday.com/1556596828041.html, src/extractors/custom/index.js, src/extractors/custom/www.rbbtoday.com/index.js, src/extractors/custom/www.rbbtoday.com/index.test.js
=> feat: add rbbtoday.com custom parser

src/mercury.test.js
I've removed duplicate test, which just had different name, but the exactly same sources.
=> tests: remove a duplicate test

package.json, yarn.lock
=> chore: Update jQuery to 3.5.0

src/extractors/custom/postlight.com/index.test.js
The most recent changes to the Postlight custom parser required an update to one of the unit tests. This PR will get the main branch back into a healthy state with all tests passing.
=> fix: postlight parser test
